[package]
name = "lox_rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "jlox", "clox" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

[dependencies]
jlox = { path = "jlox" }
clox = { path = "clox" }
